language: objective-c
osx_image: xcode10
xcode_project: twiliochat.xcodeproj
xcode_scheme: twiliochat

before_install:
  # - travis_wait pod repo update >/dev/null 2>&1

install:
  # - travis_wait pod install
  - echo "Do not install"

script:
  # - xctool -sdk iphonesimulator -workspace twiliochat.xcworkspace -scheme twiliochat test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - echo "xctool doesn't support xcode8 currently. Will fix that later"
