language: objective-c
osx_image: xcode7.1
xcode_project: twiliochat.xcodeproj
xcode_scheme: twiliochat

install:
  - travis_wait pod install

script:
  - xctool -sdk iphonesimulator -workspace twiliochat.xcworkspace -scheme twiliochat test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
